### Interpreting Coefficients

It is important that not only can you fit complex linear models, but that you then know which variables you can interpret. 

In this notebook, you will fit a few different models and use the quizzes below to match the appropriate interpretations to your coefficients when possible.

In some of the cases, the coefficients of your linear regression models wouldn't be kept due to the lack of significance, that is not the aim of this notebook - **this is strictly to assure you are comfortable with how to interpret coefficients (when they are interpretable at all**.

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm;

df = pd.read_csv('02-Dataset/house_prices.csv')
df.head()

   house_id neighborhood  area  bedrooms  bathrooms      style    price
0      1112            B  1188         3          2      ranch   598291
1       491            B  3512         5          3  victorian  1744259
2      5952            B  1134         3          2      ranch   571669
3      3525            A  1940         4          2      ranch   493675
4      5108            B  2208         6          4  victorian  1101539

We will be fitting a number of different models to this dataset throughout this notebook.  For each model, there is a quiz question that will allow you to match the interpretations of the model coefficients to the corresponding values.  If there is no 'nice' interpretation, this is also an option!

### Model 1

`1.` For the first model, fit a model to predict `price` using `neighborhood`, `style`, and the `area` of the home.  Use the output to match the correct values to the corresponding interpretation in quiz 1 below.  Don't forget an intercept!  You will also need to build your dummy variables, and don't forget to drop one of the columns when you are fitting your linear model. It may be easiest to connect your interpretations to the values in the first quiz by creating the baselines as neighborhood **C** and home style **lodge**.

In [2]:
# Copying df.
df_m1 = df.copy()

In [9]:
# Adding the intercept.
df_m1['intercept'] = 1

# Converting the neighborhood categorical in dummies variables.
df_m1[['A','B','C']] = pd.get_dummies(df_m1['neighborhood'])

# Converting the style categorical in dummies variables.
df_m1[['lodge','ranch','victorian']] = pd.get_dummies(df_m1['style'])

# Priting the first 5 rows.
df_m1.head()

,house_id,neighborhood,area,bedrooms,bathrooms,style,price,intercept,A,B,C,lodge,ranch,victorian
0,1112,B,1188,3,2,ranch,598291,1,0,1,0,0,1,0
1,491,B,3512,5,3,victorian,1744259,1,0,1,0,0,0,1
2,5952,B,1134,3,2,ranch,571669,1,0,1,0,0,1,0
3,3525,A,1940,4,2,ranch,493675,1,1,0,0,0,1,0
4,5108,B,2208,6,4,victorian,1101539,1,0,1,0,0,0,1

In [20]:
# C and lodge as baseline.
lm_m1 = sm.OLS(df_m1['price'],df_m1[['intercept','area', 'A', 'B', 'ranch', 'victorian']])

# Calculating the coefficients.
results = lm_m1.fit()

# Priting the summary
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.919
Model:                            OLS   Adj. R-squared:                  0.919
Method:                 Least Squares   F-statistic:                 1.372e+04
Date:                Fri, 11 Jan 2019   Prob (F-statistic):               0.00
Time:                        12:17:11   Log-Likelihood:                -80348.
No. Observations:                6028   AIC:                         1.607e+05
Df Residuals:                    6022   BIC:                         1.607e+05
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
intercept  -1.983e+05   5540.744    -35.791      0.000   -2.09e+05   -1.87e+05
area         348.7375      2.205    158.177      0.000     344.415     353.060
A           -194.2464   4965.459     -0.039      0.969   -9928.324    9539.832
B           5.243e+05   4687.484    111.844      0.000    5.15e+05    5.33e+05
ranch      -1974.7032   5757.527     -0.343      0.732   -1.33e+04    9312.111
victorian  -6262.7365   6893.293     -0.909      0.364   -1.98e+04    7250.586
==============================================================================
Omnibus:                      114.369   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              139.082
Skew:                           0.271   Prob(JB):                     6.29e-31
Kurtosis:                       3.509   Cond. No.                     1.12e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.12e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [21]:
-1.983e+05 -194.2464

-198494.2464

### Model 2

`2.` Now let's try a second model for predicting price.  This time, use `area` and `area squared` to predict price.  Also use the `style` of the home.  You will again need to use your dummy variables, and add an intercept to the model.  Use the results of your model to answer quiz 2 and quiz 3.

In [23]:
# Copying df.
df_m2 = df.copy()

In [29]:
# Adding the intercept.
df_m2['intercept'] = 1

# Adding higher order term.
df_m2['area_squared'] = df_m2['area'] * df_m2['area']

# Converting the neighborhood categorical in dummies variables.
df_m2[['A','B','C']] = pd.get_dummies(df_m2['neighborhood'])

# Converting the style categorical in dummies variables.
df_m2[['lodge','ranch','victorian']] = pd.get_dummies(df_m2['style'])

# Priting the first 5 rows.
df_m2.head()

,house_id,neighborhood,area,bedrooms,bathrooms,style,price,area_squared,lodge,ranch,victorian,A,B,C,intercept
0,1112,B,1188,3,2,ranch,598291,1411344,0,1,0,0,1,0,1
1,491,B,3512,5,3,victorian,1744259,12334144,0,0,1,0,1,0,1
2,5952,B,1134,3,2,ranch,571669,1285956,0,1,0,0,1,0,1
3,3525,A,1940,4,2,ranch,493675,3763600,0,1,0,1,0,0,1
4,5108,B,2208,6,4,victorian,1101539,4875264,0,0,1,0,1,0,1

In [31]:
# C and lodge as baseline.
lm_m2 = sm.OLS(df_m2['price'],df_m2[['intercept','area', 'area_squared','ranch', 'victorian']])

# Calculating the coefficients.
results = lm_m2.fit()

# Priting the summary
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.678
Model:                            OLS   Adj. R-squared:                  0.678
Method:                 Least Squares   F-statistic:                     3173.
Date:                Fri, 11 Jan 2019   Prob (F-statistic):               0.00
Time:                        12:41:35   Log-Likelihood:                -84516.
No. Observations:                6028   AIC:                         1.690e+05
Df Residuals:                    6023   BIC:                         1.691e+05
Df Model:                           4
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
intercept     1.855e+04   1.26e+04      1.467      0.142   -6229.316    4.33e+04
area           334.0146     13.525     24.696      0.000     307.501     360.528
area_squared     0.0029      0.002      1.283      0.199      -0.002       0.007
ranch         9917.2547   1.27e+04      0.781      0.435    -1.5e+04    3.48e+04
victorian     2509.3956   1.53e+04      0.164      0.870   -2.75e+04    3.25e+04
==============================================================================
Omnibus:                      375.220   Durbin-Watson:                   2.009
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              340.688
Skew:                           0.519   Prob(JB):                     1.05e-74
Kurtosis:                       2.471   Cond. No.                     4.33e+07
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.33e+07. This might indicate that there are
strong multicollinearity or other numerical problems.
"""